### ISSUE TITLE
Faster videos after use FileVideoStream from imutils even when I don't use FileVideoStream

### ISSUE THREAD

**Issue by GabySol** [jrosebr1/imutils#106]
I have an issue with FileVideoStream from imutils, this help to encrease the fps of a video using threading, and It worked well, but now when I try to display any other video, it get faster even if I don't use FileVideoStream. I tried a simple example with OpenCV: [Playing Video from file](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html), but the video plays faster than its real speed.

    import numpy as np
    import cv2
    import threading

    cap = cv2.VideoCapture('prueba00001.avi')

    while(cap.isOpened()):
	   ret, frame = cap.read()

	   print ('threading.active_count())=',threading.active_count())
	   gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
	
	   cv2.imshow('frame',gray)
    
	   if cv2.waitKey(1) & 0xFF == ord('q'):
	   	break
	
    cap.release()
    cv2.destroyAllWindows()

I tried to know if there were active threads but, there was only one. Then I created another virtualenv, I installed OpenCV, then I ran the code above, but I got the same faster video. I'm using Python 3.

**Comment by jrosebr1** [comment]
> it get faster even if I don't use FileVideoStream. I tried a simple example with OpenCV: Playing Video from file, but the video plays faster than its real speed.

This is a feature of OpenCV, not a bug. The goal of OpenCV is real-time image/video processing. OpenCV doesn't care what the FPS is of the video that was recorded, it instead wants to process frames as fast as it possibly can. Therefore, if your pipeline is highly simplistic, like yours is, videos will be processed faster than the rate they were originally recorded.

Again, that's a feature, not a bug.

**Comment by GabySol** [comment]
Thank you so much Adrian, you are a pyimagesearch hero! I'm a huge fan of your posts, It's wonderful how you share your knowledge, again thanks!

**Comment by ashpadma** [comment]
But I want to read and display according to the frame rate it was recorded in. How do I do that?
Please help @jrosebr1
