### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by Twikkxx** [jrosebr1/imutils#114]
Traceback (most recent call last):
  File "/home/pi/Desktop/realtime/realtime.py", line 85, in <module>
    (cnts, _) = contours.sort_contours(cnts)
  File "/usr/local/lib/python3.5/dist-packages/imutils/contours.py", line 26, in sort_contours
    key=lambda b: b[1][i], reverse=reverse))
ValueError: not enough values to unpack (expected 2, got 0)

Hi I'am trying to implement a real time Object size detection on my raspberry pi from this tutorial https://www.pyimagesearch.com/2016/03/28/measuring-size-of-objects-in-an-image-with-opencv/
in works perfectly fine on measuring the size of the objects in the images but when I try to modify it to measure real time objects this error keeps on occurring.

**Comment by jrosebr1** [comment]
How are you obtaining the `cnts` variable? And which version of OpenCV are you using?

**Comment by omkarpatil0117** [comment]
Having same  problem. I am completely new to programming.

Error -

Traceback (most recent call last):
  File "D:\STUDY\Final year Project\Codes\Video Thresholding.py", line 38, in <module>
    cnts = contours.sort_contours(cnts)[0]
  File "C:\python 37\lib\site-packages\imutils\contours.py", line 24, in sort_contours
    (cnts, boundingBoxes) = zip(*sorted(zip(cnts, boundingBoxes),key=lambda b: b[1][i], reverse=reverse))
ValueError: not enough values to unpack (expected 2, got 0)

cnts variable are obtained as - 

cnts = cv2.findContours(mask.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    cnts = contours.sort_contours(cnts)[0]

OpenCV  version 4.0.0

Any help would be appreciated .Please Reply soon if you read this.

**Comment by jrosebr1** [comment]
Check the `len(cnts)`. If zero contours are detected then there is nothing to sort -- that sounds like the issue here. You should check to see if you found contours before passing them into the function:

```
if len(cnts) > 0:
    cnts = contours.sort_contours(cnts)[0]
```

**Comment by omkarpatil0117** [comment]
Thank you very much sir ,thay solved my problem.
