### ISSUE TITLE
Rounding in resize is wrong

### ISSUE THREAD

**Issue by yakirsudry** [jrosebr1/imutils#115]
example: 
image.shape == (500, 1000, 3)
resize(image, width=2018)
wil return an image of dimensions(1008, 2018)

The reason is the lines
r = width / float(w)
dim = (width, int(h * r))

which should round the dimension instead of flooring it

**Comment by jrosebr1** [comment]
It's perfectly normal to simply cast the floating point value as an integer. I don't see this as a bug. Please feel free to create your own `resize` function and round if you would like.
