### ISSUE TITLE
Memory leak in video stream. 

### ISSUE THREAD

**Issue by LordSycho** [jrosebr1/imutils#116]
Hi,  Below is the code that can reproduce memory leak. I am running it in a scheduler. Please guide me how i can release the memory, or any guidance why the memory is increasing. 

````
import cv2
import os
from imutils.video import VideoStream
from time import time, sleep
from flask import Flask
from flask_cors import CORS, cross_origin
from apscheduler.schedulers.background import BackgroundScheduler
import psutil
import gc

camera_url = "rtsp://admin:admin@10.1.7.50:554/cam/realmonitor?channel=1&subtype=0"

t_start = time()
vs = VideoStream(camera_url).start()
print("time taken to access camera : " + str(time() - t_start))


def read_and_check_memory ():
	global vs
	process = psutil.Process(os.getpid())

	print("memory used before grabbing  : " + str(process.memory_info().rss))
	frame = vs.read()
	print("memory used after grabbing  : " + str(process.memory_info().rss))
	gc.collect()
app = Flask(__name__)
CORS(app)

if __name__ == "__main__":
	scheduler = BackgroundScheduler()  # Starting a scheduler to schedule the algorithm
	scheduler_job1 = scheduler.add_job(func=read_and_check_memory, trigger="interval",
									   seconds=10)
	if scheduler.state != "STATE_RUNNING":
		scheduler.start()
	app.run(port=33333)

````

Output : 

memory used before grabbing  : 57921536
memory used after grabbing  : 57921536
memory used before grabbing  : 57942016
memory used after grabbing  : 57942016
memory used before grabbing  : 57933824
memory used after grabbing  : 57933824
memory used before grabbing  : 57958400
memory used after grabbing  : 57958400
memory used before grabbing  : 57982976
memory used after grabbing  : 57982976
memory used before grabbing  : 58003456
memory used after grabbing  : 58003456
memory used before grabbing  : 58028032
memory used after grabbing  : 58032128
memory used before grabbing  : 58048512
memory used after grabbing  : 58048512
memory used before grabbing  : 58073088
memory used after grabbing  : 58073088
memory used before grabbing  : 58093568
memory used after grabbing  : 58093568
memory used before grabbing  : 58101760
memory used after grabbing  : 58101760
memory used before grabbing  : 58105856
memory used after grabbing  : 58105856
memory used before grabbing  : 58109952
memory used after grabbing  : 58109952
memory used before grabbing  : 58109952
memory used after grabbing  : 58109952
memory used before grabbing  : 58109952
memory used after grabbing  : 58109952
memory used before grabbing  : 58114048
memory used after grabbing  : 58114048
memory used before grabbing  : 58118144
memory used after grabbing  : 58118144
memory used before grabbing  : 58118144
memory used after grabbing  : 58118144
memory used before grabbing  : 58122240
memory used after grabbing  : 58122240
memory used before grabbing  : 58126336
memory used after grabbing  : 58126336
memory used before grabbing  : 58134528
memory used after grabbing  : 58134528
memory used before grabbing  : 58134528
memory used after grabbing  : 58134528
memory used before grabbing  : 58118144
memory used after grabbing  : 58118144
memory used before grabbing  : 58134528
memory used after grabbing  : 58134528
memory used before grabbing  : 58134528
memory used after grabbing  : 58134528
memory used before grabbing  : 58134528
memory used after grabbing  : 58134528
memory used before grabbing  : 58134528
memory used after grabbing  : 58134528
memory used before grabbing  : 58150912
memory used after grabbing  : 58150912
memory used before grabbing  : 58150912
memory used after grabbing  : 58150912
memory used before grabbing  : 58150912
memory used after grabbing  : 58150912
memory used before grabbing  : 58150912
memory used after grabbing  : 58150912
memory used before grabbing  : 58150912
memory used after grabbing  : 58150912
memory used before grabbing  : 58150912
memory used after grabbing  : 58150912
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58191872
memory used after grabbing  : 58191872
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58195968
memory used after grabbing  : 58195968
memory used before grabbing  : 58200064
memory used after grabbing  : 58200064

Please take a look, I am trying to access multiple cameras the above output is of one camera. 
So in a multi camera flow, this is creating a huge memory leak.

**Comment by jrosebr1** [comment]
I would suggest using Python's debugger, `pdb`, to debug that further. Additionally, this doesn't sound like an issue with the `VideoStream` class itself -- it could be a problem with OpenCV's `cv2.VideoCapture` function. If you search [OpenCV's open Issues](https://github.com/opencv/opencv/issues) you'll find a number of references to memory leaks. That could be what is happening there. I suggest you post on the OpenCV GitHub after utilizing `pdb`. I'm going to close this for now but feel free to reopen if you find anything else you would like to share/anything else pops up showing that is indeed an issue related to `VideoStream`.
