### ISSUE TITLE
Any interest in convenience function(s) for centering text?

### ISSUE THREAD

**Issue by AdamSpannbauer** [jrosebr1/imutils#117]
Hi @jrosebr1,

Before putting in the work to build up a PR I wanted to check if there would be any interest in the idea.

I recently had the need to center text both vertically and horizontally.  I also wanted the ability to place line breaks in the same centered text.  I came up with functions to create the below output.

If there was interest I was thinking something along the lines of a function named something like `put_centered_text` (to mirror the name of `cv2.putText`).  The function could have options to center vertically and/or horizontally.  Thoughts?

![image](https://user-images.githubusercontent.com/16326083/52536733-7e29f280-2d2c-11e9-979f-03ec819a9a37.png)

**Comment by jrosebr1** [comment]
I really like the idea, thanks for suggestion it @AdamSpannbauer. Working with `cv2.putText` can be a major pain for multi-line output but it looks like you've put together a nice solution 😄 

Feel free to open up a PR but make sure the `put_centered_text` lives in an `imutils.text` module to keep the library organized.

**Comment by AdamSpannbauer** [comment]
Hi @jrosebr1,

I've added a first pass [`imutils.text`](https://github.com/AdamSpannbauer/imutils/blob/master/imutils/text.py) module to [my fork of imutils](https://github.com/AdamSpannbauer/imutils).  I just wanted to double check some items before doing some final prep for the PR (where we can critique the actual implementation details).

## 1.
The module is fairly lengthy, but this is mainly due to me including docstrings out of habit.  Would you prefer me to delete the docstrings of user facing functions to be consistent with the rest of the package?

## 2.
There are some changes to the original design plan I outlined.  I'll leave it up to you whether the scope creep is a positive or if it's doing too much.

The updated design was to implement a `put_aligned_text` text that takes `v_align` & `h_align` parameters for vertical and horizontal alignment.  The below output shows all possible combinations of the 2 parameters.

*text size/thickness has been randomized to text funcationality on multiple cases*
![image](https://user-images.githubusercontent.com/16326083/52580644-c877a600-2df6-11e9-8e01-4cc944415070.png)

**Comment by AdamSpannbauer** [comment]
....and now I've almost surely taken it too far

(in a separate branch) I extended the functionality to accommodate writing text in text boxes of arbitrary locations/dimensions.  Text boxes have optional borders based on `cv2.rectangle`.

Text box demo output using random locations, dimensions, font, and border:
![image](https://user-images.githubusercontent.com/16326083/52720507-bc662280-2f75-11e9-8f7a-53642c35d993.png)

example call:

```python
text_box_border = {'color': (255, 0, 0), 'thickness': 2}
# Bounding box format is (x, y, width, height)
put_text_box(image, 'test string', bounding_box=(50, 50, 20, 30),
             color=(0, 0, 255), font_scale=2,
             v_align='middle', h_align='center',
             border=text_box_border)
```

**Comment by jrosebr1** [comment]
Hey @AdamSpannbauer -- I agree, this might be a fit too far 😉, but it's really cool to see. I think the second option would be a good fit for `cvui`:

https://dovyski.github.io/cvui/

I might propose the second PR to them.

But for the purpose of `imutils`, let's use your first suggestion. Please create the PR and I'll merge it in 😄
