### ISSUE TITLE
Why we need time.sleep() after FileVideoStream()?

### ISSUE THREAD

**Issue by Zc631n** [jrosebr1/imutils#120]
Hi
1) What is the reason to have time.sleep() after calling FileVideoStream()?
2) What is the shortest sleep time that is safe to be used? (in my application I need to have the shortest sleep time)

Thanks

**Comment by jrosebr1** [comment]
The `time.sleep` allows the initial buffer to fill up. You don't technically _have_ to do this but I recommend a small sleep before starting. As to how fast a buffer fills up is really dependent on your hardware, drivers, video file I can't really provide a "shortest time" -- you will need to experiment with that on your own.

I hope that helps!
