### ISSUE TITLE
Increasing webcam FPS to increase YOLO stream video speed

### ISSUE THREAD

**Issue by aychaAlsattouf** [jrosebr1/imutils#122]
Hello;
you mention in https://www.pyimagesearch.com/2015/12/21/increasing-webcam-fps-with-python-and-opencv/
How can we increase FPS rate by doing threading , my question is can i use it with YOLO also because it goes too slow~ 0.3FPS on Raspberry pi3b+

**Comment by jrosebr1** [comment]
The vast majority of deep learning-based object detectors are going to run far, far too slow on a Pi. The Pi just isn't powerful enough. You should consider using a Movidius NCS to increase your FPS throughput rate. Threading alone on the video stream is not your bottleneck here.

**Comment by aychaAlsattouf** [comment]
@jrosebr1 thanks for your help

**Comment by aychaAlsattouf** [comment]
yeah it was far too slow 
thanks for your help
