### ISSUE TITLE
About Face recognition

### ISSUE THREAD

**Issue by Hamdikap** [jrosebr1/imutils#123]
When ı want run your face recognizer algorithm  ı get issue from your extrack_embeddings.py it's about 

 File "extract_embeddings.py", line 116, in <module>
    f.write(pickle.dumps(data))
OSError: [Errno 9] Bad file descriptor

Can we solve it ?

**Comment by jrosebr1** [comment]
That's not related to the `imutils` library. If you have a question related to face recognition please post it on the appropriate PyImageSearch blog post and I will address there.
