### ISSUE TITLE
make is not recognized as an internal or external command while make" under coco /PythonAPI  #142

### ISSUE THREAD

**Issue by Samjith888** [jrosebr1/imutils#128]
I'm training own images by using [https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10](this tutorial). I almost done with labelling and all. While running the training i got error "Import error : cnnot import name coco". So i go for make command **make" under coco /PythonAPI**  #142 , i'm getting the following error.

`make is not recognized as an internal or external command` Operable program or batch file 

working environment:
Windows 7
Python 3.6
Tensorflow cpu 1.5.0
Protobuf 3.6.0

**Comment by jrosebr1** [comment]
This doesn't have anything to do with the imutils library. Please post it on the appropriate GitHub Issues page.
