### ISSUE TITLE
Not compatible with jupyter notebook

### ISSUE THREAD

**Issue by Dhruvilhapani** [jrosebr1/imutils#133]
Installed imutils with pip and pip3 "install imutils". 
I am unable to import it in the ipython notebook. It does import in python directly through the terminal, but cannot find the library in notebook.

**Comment by jrosebr1** [comment]
The `imutils` library is 100% compatible with Jupyter Notebooks. The issue you are running into isn't related to the library, it's with your environment. It sounds like your Jupyter Notebook is using a different Python environment (or a Python virtual environment). Double and triple check that you have installed `imutils` into the correct environment.
