### ISSUE TITLE
Help in grab_contour

### ISSUE THREAD

**Issue by arumrum** [jrosebr1/imutils#134]
hai..my name is arum I new in python
and i am recently trying your code, but my imutils.grab_contours modules is not found. I already upgrade to version 0.52.

Anything could I do wrong?  Thank you for your time answering my question

**Comment by arumrum** [comment]
[](url)
![image](https://user-images.githubusercontent.com/24473216/55679448-11029a00-5936-11e9-9329-4fc457502fcd.png)

And I also find this error. When I search for the function, drawContours is found but cannt be called in program
![image](https://user-images.githubusercontent.com/24473216/55679470-5e7f0700-5936-11e9-8cf6-e064924a8d6b.png)

**Comment by jrosebr1** [comment]
You're confusing OpenCV and imutils functions. The function you are looking for is `imutils.grab_contours`. The `imutils.find_function` is used to search the `cv2` for function names. 

Finally, it's `cv2.drawContours`.
