### ISSUE TITLE
Attribute Error: module 'imutils' has no attribute 'grab_contours'

### ISSUE THREAD

**Issue by WOOSH1806** [jrosebr1/imutils#135]
I am currently trying to understand a ball tracking program, which uses the feature of contours as a part of detecting the ball. On running the program, i get the following error:

cnts = imutils.grab_contours(cnts)

AttributeError: module 'imutils' has no attribute 'grab_contours'

Can anybody help me out to solve this issue? I am executing this program on Spyder and have the 3.6.3 version of Python. The imutils package version is 0.4.6

Thank you!

**Comment by jrosebr1** [comment]
You are using an old version of `imutils`. You need to upgrade:

`$ pip install --upgrade imutils`

**Comment by ibrahimqazi** [comment]
@jrosebr1 hello i have the same problem and my imutils is already newest version but still the same problem.
Requirement already up-to-date: imutils in /usr/local/lib/python2.7/dist-packages (0.5.2)

**Comment by theshawnz** [comment]
A little late...but for the benefit of others: I too was encountering this issue (having the latest installed but no success) and concluded that it was due to not working within the correct environment.
