### ISSUE TITLE
installing imutils

### ISSUE THREAD

**Issue by naruto1980** [jrosebr1/imutils#138]

**Comment by naruto1980** [comment]
Hi,
when I use 
`import imutils`
I got
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'imutils'
```
but if I install imutils

```
pip install imutils
Requirement already satisfied: imutils in c:\users\thang\anaconda3\lib\site-packages (0.4.6)
```

or 

```
pip install --upgrade imutils
Collecting imutils
Installing collected packages: imutils
  Found existing installation: imutils 0.4.6
Cannot uninstall 'imutils'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by jrosebr1** [comment]
This is an issue with your Python environment and your Python path. Without having access to your machine I unfortunately cannot debug the problem. My suggestion for you is to debug your Python path, it's likely an issue caused by Python paths between your system Python and your Anaconda Python.

**Comment by ccworld1000** [comment]
I have the same problem. But I've run it before, no problem.
It hasn't been running for a long time. There is something wrong with this operation.
Is it more relevant to upgrade the system environment?
I have upgraded to MacOS 10.14.3

This time, I tried to install and uninstall the same errors again and again. Do you want to check them?

**Comment by ccworld1000** [comment]
![BA9CBB58-1E1B-4926-AC52-282EFEAC2C85](https://user-images.githubusercontent.com/22360168/56792770-ea50c880-683c-11e9-8a52-acf6262b656e.png)
