### ISSUE TITLE
ImportError: No module named 'scipy'

### ISSUE THREAD

**Issue by remort** [jrosebr1/imutils#141]
Using `four_point_transform` in my code causing scipy import which is not installed on my raspberry pi after installing imutils. So I think scipy is absent in imutils requirements.
```
  File "/home/pi/whiteboard-device/calibrate_utils.py", line 5, in <module>
    from imutils.perspective import four_point_transform
  File "/usr/local/lib/python3.5/dist-packages/imutils/perspective.py", line 5, in <module>
    from scipy.spatial import distance as dist
```

**Comment by metric-space** [comment]
Perhaps you missed [this](https://github.com/jrosebr1/imutils#installation) in the README

> Provided you already have NumPy, **SciPy**, Matplotlib, and OpenCV already installed, the imutils package is completely pip-installable:

**Comment by remort** [comment]
Does it mean that pip-package shouldn't have packages mentioned above as dependencies ?

**Comment by jrosebr1** [comment]
@remort The `imutils` library is also meant to be compatible with resource constrained devices such as the RPi. Compiling and installing SciPy on a RPi can take _hours_. Therefore, I don't make SciPy a requirement to be installed.
