### ISSUE TITLE
Error in import "imutils" package after I installed 

### ISSUE THREAD

**Issue by Elwakdy** [jrosebr1/imutils#146]
Hi Everybody,

I am using Python 2.7 and Windows 7. 

After I installed the "imutils" package and "Opencv" package as below, all these packages installed successfully :

pip install opencv-python

pip install opencv-contrib-python

pip install imutils 

But when I started to import these packages, the opencv package has only imported, but I have received this error when I imported "imutils" package:

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    import imutils
  File "D:\Python 27\lib\site-packages\imutils\__init__.py", line 8, in <module>
    from .convenience import translate
  File "D:\Python 27\lib\site-packages\imutils\convenience.py", line 65, in <module>
    def resize(image, width=None, height=None, inter=cv2.INTER_AREA):
AttributeError: 'module' object has no attribute 'INTER_AREA'

I would be happy if you can advise me some steps to do to fix this error. 

Thanks in advance

**Comment by jrosebr1** [comment]
That's a problem with however you installed OpenCV on your system. Please keep in mind that while I provide this tutorial and all the PyImageSearch tutorials for free, I do not support Windows as an OS. Additionally, Python 2.7 is _rapidly_ approaching its end of life (I would suggest you use Python 3).

Again, take a look at how you installed OpenCV as that's 99.9% likely the issue.

**Comment by Elwakdy** [comment]
Hi,

I faced the same problem when I worked on python 3, as I don'y have a
problem in installing open cv. I would be happy if you can send me a
tutorial help me in fixing the error.

Thanks a lot

Mohamed Elwakdy

**Comment by jrosebr1** [comment]
Sorry, as I mentioned, I don't support Windows. If you'd like to try with a Linux or macOS machine I could provide suggestions.

**Comment by sabritol** [comment]
Hi! I have the same problem and I'm running in Linux

**Comment by chenlize96** [comment]
For Linux users: there should not be any issues.
For Windows users like me:
Download opencv_python-4.5.5-cp38-cp38-win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv
pip3 install opencv_python-4.5.5-cp38-cp38-win_amd64.whl
Then it should be okay.
