### ISSUE TITLE
How can I prepare the dataframe if the independent variable has a special format 

### ISSUE THREAD

**Issue by Elwakdy** [jrosebr1/imutils#150]
Hi Everybody, 

I am using Python 3.7. I am working to prepare a dataset before building a predictive model. One of the independent variables called 'path_id_set' in the dataframe as below. The 'path_id_set' is defined in the dataset as all the locations that were visited during the session.

df= 
0                                              "31672;0"
1                                              "31965;0"
2                                              "0;78464"
3                                                  51462
4                                              "31931;0"
5                                                      0
6                                                      0
7                                              "34302;0"
8                                              "34227;0"
9                                        "42172;0;38715"
10                                       "0;45069;44232"
11                                            "463209;0"
12                                              "9644;0"
 
I tried to solve this issue, but it doesn't work:

from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
mlb.fit_transform(df['path_id_set'].str.split(';'))

I need your help to fix this issue. 

Thanks in advanced

**Comment by jrosebr1** [comment]
Do not use the `imutils` GitHub repo to submit questions unrelated to the library. If you have a question regarding scikit-learn's `MultiLabelBinarizer` consider posting it on StackOverflow or their GitHub Issues.

**Comment by 1ahmaddiab** [comment]
How did you solve this issue?
I am using R and still confused about the 'path_id_set' variables and what to do with the ';' ?
