### ISSUE TITLE
Unblocking video thread with async/await?

### ISSUE THREAD

**Issue by JeffJassky** [jrosebr1/imutils#154]
Is it possible to use async/await on a VideoStream consumer?

The application is a Raspberry Pi Cam controlled by a Websockets to update settings, enable/disable preview, capture stills/streams, enable certain opencv-based features. I need to be able to process incoming requests but the while loop for processing VideoStream.read() is blocking the thread.

Any suggestions?

**Comment by jrosebr1** [comment]
Hey @JeffJassky -- I believe I've already answered this question over email, no? That or someone emailed me with the exact same question. Going to close it out.
