### ISSUE TITLE
VideoStream Issue: FATAL: exception not rethrown

### ISSUE THREAD

**Issue by cheeyeo** [jrosebr1/imutils#164]
```
Python version: 3.6.8

imutils version: 0.5.3

OS: Ubuntu 18.04
```

While running an instance of `VideoStream` to capture images from a webcam, the program will exit at the end with the following error message:

```
FATAL: exception not rethrown
Aborted (core dumped)
```
I'm not sure if this is related to the issue mentioned in https://github.com/jrosebr1/imutils/issues/38 but it does have the same error.

I tried putting in a sleep before closing the video stream but it has no effect.

Is there anyway to resolve this issue?

Thank you for a great lib.

**Comment by jrosebr1** [comment]
That definitely sounds like a threading related issue. Unfortunately I do not have the time to debug the matter further -- I'm simply too busy publishing content on PyImageSearch.

**Comment by leematthewshome** [comment]
I am getting the same issue with the FaceIdentification sample code from pyImagesearch. 
Interestingly, I removed use of imutils by using equivalent cv2 functions and the issue still persists. So it cannot be imutils. It must be something to do with cv2.

**Comment by cheeyeo** [comment]
Hi @leematthewshome thanks for the feedback. I will close this for now as I also have no idea how to debug cv2.
