### ISSUE TITLE
threaded frame rate slower than speficied

### ISSUE THREAD

**Issue by Amrosik** [jrosebr1/imutils#17]
I have a code example, where the processing pipe's throughput is about 23 fps, while the framerate of PiVideoStream is specified to be 40. See the following code:

```
from __future__ import print_function
from imutils.video.pivideostream import PiVideoStream
from imutils.video import FPS
import imutils
import time
import cv2


# function to return the difference of elementsums between consecutive frames. If it returns 0, 
# then  the frames are identical with a high probability

def diff(frame1,frame2):
    return(cv2.sumElems(frame1)[0]-cv2.sumElems(frame2)[0])

vs = PiVideoStream(resolution=(720,720),framerate=40).start()
time.sleep(2.0)
fps = FPS().start()
diffs=[]
frame2 = vs.read()
while fps._numFrames < 50:
    frame1 = frame2
    time.sleep(0.025)
    frame2 = vs.read()
    diffs.append(diff(frame1,frame2))
    fps.update()


fps.stop()
print("[INFO] elasped time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))
print(diffs)

cv2.destroyAllWindows()
vs.stop()
```
The script is doing the following:

comparing two consecutive frames by subtracting the elementsums of each from each other. If the result is zero, then the frames must have been identical (since the scene is not static). The for loop is looping through several frames and storing consecutive differences to 'diffs'.

Remember, according to imutils.video.FPS my throughput is 23 frames per second. Therefore if the camera framerate is 40, and the PiVideoStream is actually working like it is supposed to do, then the elements of `diffs` should be all non-zero. But in fact up to 40% of the elements are zero. try it out
The camera itself is surely able to handel 40fps. So there must be something with the implementation of threading.

**Comment by jrosebr1** [comment]
Keep in mind that the `PiVideoStream` and related classes *does not guarantee* new frames at each iteration of your loop. The thread simply runs in the background and the `frame` object is updated whenever a new one is polled from the camera. If your video processing pipeline is *faster* than your physical camera, this is totally a possibility.

I'm marking this as closed since this is the intended functionality.

**Comment by Amrosik** [comment]
The processing pipeline is not faster than the physical framerate. But the processing pipeline is faster than PiVideoStream is able to call update(). the read() method inside the procesing loop is called quicker than the threaded video stream is able to truncate the stream.

**Comment by jrosebr1** [comment]
> The rate, at which PiVideoStream is pooling frames is lower than the potential camera-framerate specified.

In my experience, using OpenCV + Python on the Pi it's extremely challenging it even obtain the specified camera framerate. I would suggest running more tests, this time completely removing any threading code, and then measuring the FPS and see how performance changes.

I actually think this this question would likely be better suited for the [picamera Issues](https://github.com/waveform80/picamera/issues) rather than imutils. Keep in mind that `PiVideoStream` simply wraps `picamera`, but in a threaded manner.

If `.read` is being called multiple times before `.truncated` can be called, then that is a limitation at the library level of `picamera` not being able to poll frames fast enough, no? In fact, your `time.sleep` is evidence of this. The process of clearing the buffer and reading the next frame takes longer than the time it takes to sleep and then call `.read`. From a `PiVideoStream` perspective, I don't think there is much you can do about that -- that resides at the `picamera` level. Again, just because you specify a framerate of 40, doesn't mean that you'll actually get a framerate of 40 out of the library.

**Comment by Amrosik** [comment]
So polling takes at least 0.1 seconds? Then there is no point in exceeding 10fps with this method. I think it should be faster to poll frames from capture_sequence. Is it possible to created a threaded frame polling based of capture_sequence?

**Comment by jrosebr1** [comment]
It depends on the size of your frame. Smaller frames are read much faster. Change the frame size to 320x240 and you'll see *much* faster reads. As for a threaded capture from capture_sequence, you'll need to check with the picamera developers.

**Comment by Amrosik** [comment]
I found a way to create a threaded stream using capture_sequence. below an example for direct grayscale capture:
```


import io
import time
from picamera import PiCamera
import cv2
import numpy
from threading import Thread
import time


w=640
h=480
fw=(w+31)//32*32
fh=(h+15)//16*16
Y=None
camera=PiCamera()
camera.resolution = (w, h)
camera.framerate = 40
camera.exposure_mode='off'
camera.awb_mode='off'
camera.awb_gains=1
camera.shutter_speed=15000
stream_done=False
cv2.namedWindow("detection", cv2.WINDOW_AUTOSIZE)


def diff(frame1,frame2):
    return int(cv2.sumElems(frame1)[0]-cv2.sumElems(frame2)[0])

def outputs():
    global Y
    stream = io.BytesIO()
    while not stream_done:
        
        yield stream

        stream.seek(0)
        Y=numpy.fromstring(stream.getvalue(),dtype=numpy.uint8,count=fw*fh).\
           reshape((fh,fw))
        
        stream.seek(0)
        stream.truncate()

def capt():
    camera.capture_sequence(outputs(), 'yuv', use_video_port=True)
    pass

def startcapt():
    t = Thread(target=capt, args=())
    t.daemon = True
    t.start()

##TEST 
startcapt()
time.sleep(0.5)
diffs=[]
frame2=Y
while cv2.waitKey(1) != ord("q"):
    #cv2.imshow('detection',Y)
    frame1 = frame2
    time.sleep(0.025)
    diffs.append(diff(frame1,frame2))

stream_done=True
print(diffs)
cv2.destroyAllWindows()
camera.close()
```

This one seems to be much faster, and and is able to run the Test without repetitive readouts.

**Comment by jrosebr1** [comment]
Nice, I'll be sure to play with this and test it out.

A few questions:

1. Is there a reason you changed a lot of the `camera` parameters, such as `.shutter_speed`, `.exposure_mode`, etc. Did those help you in achieving a faster FPS?

2. What are `fw` and `fh`? I see how they are computed, but I'm not sure what their actual role is when calling `np.fromsting`.

**Comment by Amrosik** [comment]
actually I did not test whether there is an impact on FPS, if you let the awb and shutter speed on auto-mode. Concerning the shutter speed, I think there will be no impact on the framerate, because the firmware adjusts the exposure time according to the specified framerate, not the other way around. The awb algorithm should have an influence. But it is executed on the gpu, so it is quick. 

For my application I had to fix these vaules to get consistent images. There is an impact on detection reliability of the hough transform. 

2.These little conversions are necessary to correctly interpret the YUV byte string. If you specify a certain resolution, say 100x100, the actual pixel count will be slighty different. The horizontal resolution is rounded up to the nearest multiple of 32 pixels, while the vertical resolution is rounded up to the nearest multiple of 16 pixels. Thats how the camera chip stores the information. for 100x100 specified, the actual size of `Y` would be 128x112, but since you specified the resolution at camera.resolution, a few overhanging pixels will be uninitialized.
For those who want rgb, just remove the 'yuv' in the capture_sequence, and you also dont need w,h,fh,fw anymore. the resolution is speficied with camera.resolution. also you need to change

```
Y=numpy.fromstring(stream.getvalue(),dtype=numpy.uint8,count=fw*fh).\
           reshape((fh,fw))
```
to 

```
frame=numpy.fromstring(stream.getvalue(),dtype=numpy.uint8)
```

**Comment by Amrosik** [comment]
I found a problem: at high resolutions there is a really anoying latency.

**Comment by jrosebr1** [comment]
Thank you for the added details @Amrosik, it's much appreciated!
