### ISSUE TITLE
No module named imutils in jupyter notebook

### ISSUE THREAD

**Issue by 8861227147** [jrosebr1/imutils#192]
I have imported library called build_montage and paths from imutils module in yupyter notebook. The code is:- 
from imutils import build_montages 
from imutils import paths

But it shows ModuleNotFoundError: no module named 'imutils'

**Comment by jrosebr1** [comment]
It's very likely that you did not install the `imutils` library correctly. Double-check that you have installed it, verify that if you are using a virtualenv that it's installed there, and finally make sure you don't have any files named `imutils.py` in your working path.
