### ISSUE TITLE
No module named 'imutils' after pip install

### ISSUE THREAD

**Issue by benstadin** [jrosebr1/imutils#24]
I just followed this guide here to install OpenCV: http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/

And then followed this guide here: http://www.pyimagesearch.com/2016/02/08/opencv-shape-detection/

I've pip-installed imutils, but keep getting the error below. 

```
sudo pip install imutils
...
Collecting imutils
  Downloading imutils-0.4.2.tar.gz
Installing collected packages: imutils
  Running setup.py install for imutils ... done
Successfully installed imutils-0.4.2
hdmih0445m:shape-detection bstadin$ 
```

The install seems to be ok, trying to reinstall imutils gives:

`Requirement already satisfied: imutils in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
`

Running a script importing imutils:

```
python3 detect_shapes.py --image /Users/bstadin/Downloads/image.png
...
Traceback (most recent call last):
  File "detect_shapes.py", line 7, in <module>
    import imutils
ModuleNotFoundError: No module named 'imutils'
```

**Comment by saschwarz** [comment]
It looks like you `pip` installed `imutils` in python2 and you are using it in python3.

**Comment by FariborzN** [comment]
for imutlis package 
if you got erorre uninstall it with`sudo pip3 uninstall imutils`
and then use ` sudo pip3 install --upgrade imutils`
if you use python2 use pip insted pip3 for instalation and unistallation

**Comment by radhikatv** [comment]
I am trying to install imutils using :
conda install -c mlgill imutils 

and I get the below error

Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - imutils
  - ruamel_yaml

**Comment by jrosebr1** [comment]
The `imutils` library is a non-conda package. You need to install via `pip`. See this thread for more details: https://github.com/jrosebr1/imutils/issues/36

**Comment by radhikatv** [comment]
Hi Adrian

Thank you. I executed the below. imutils is installed and I can see it in
Conda list from the Terminal. However, when I try to look for the package
in interpreter of Pycharm Edu, I don't see it.

conda install pip
pip install imutils

Regards,
Radhika

**Comment by jrosebr1** [comment]
Try setting the `Project Interpreter` from your PyCharm settings to point to your conda install or associated Python virtual environment.

**Comment by VishayFC** [comment]
Hey @jrosebr1 . I am using Anaconda(spyder) for image processing and was trying the ball tracking blog from your site. I wanted to install imutils and used the command pip install imutils. I can see imutils in the list but when i try to run the program again , it shows 'no module found' again. Please me help with this.

**Comment by jrosebr1** [comment]
Are you referring to the Spyder IDE? You'll need to set the project interpreter for Spyder. I don't use Spyder so I'm not sure how to do this, but for PyCharm take a look at this tutorial:

https://www.pyimagesearch.com/2015/08/17/the-perfect-computer-vision-environment-pycharm-opencv-and-python-virtual-environments/

Personally, I like executing my scripts via command line. If you're having problems executing via your IDE you can always revert to terminal.

**Comment by VishayFC** [comment]
Thanks ! Will use Pycharm now.

**Comment by ANTZ314** [comment]
Hey guys I tried the uninstall method and re-installed from both within and outside the (cv) environment and still getting the "no module named imutils" error?
Any suggestions. I've never had this problem previously.

**Comment by ANTZ314** [comment]
Hey guys I tried the uninstall method and re-installed from both within and outside the (cv) environment and still getting the "no module named imutils" error?
Any suggestions. I've never had this problem previously.

**Comment by ANTZ314** [comment]
Hey guys I tried the uninstall method and re-installed from both within and outside the (cv) environment and still getting the "no module named imutils" error?
Any suggestions. I've never had this problem previously.

**Comment by ANTZ314** [comment]
Hey guys I tried the uninstall method and re-installed from both within and outside the (cv) environment and still getting the "no module named imutils" error?
Any suggestions. I've never had this problem previously.

**Comment by jrosebr1** [comment]
Hey @ANTZ314 -- my guess is that you may have accidentally installed and uninstalled (perhaps multiple times over) the `imutils` library from your system Python install and your Python virtual environment. Here's the fool-proof method:

```
$ workon cv
$ pip install imutils
$ python
>>> import imutils
```

**Comment by HongChow** [comment]
How to fix that? @jrosebr1

**Comment by jrosebr1** [comment]
@HongChow I've answered the question many times in the thread. You'll need to be more specific regarding the exact error you are getting, operating system, and Python environment.

**Comment by KingfaLuis** [comment]
pip install imutils

**Comment by markp64** [comment]
I ran $ sudo pip install imutils
then $ python
python 3.5.2
> import imutils
ImportError: No module names 'imutils'

if run $ sudo python
Python 2.7.12
> import imutils
> (imports ok)

I had installed imutils in Python2.7 (sudo pip install imutils) and was trying to use it in Python3 (thinking I was in Python2 - PEBKAC)

Firstly, I didn't notice that I was running python3 and then python2 when using sudo.
Secondly, I had an alias entry in my .bashrc file causing the confusion: alias python='/usr/bin/python3'
Thirdly, have to be aware when using sudo, that it runs in a different user environment. (Try $ env, then $ sudo env  ). sudo is not just a security override.

**Comment by elgarmi09gt** [comment]
Hi
Note : The version of python is determine in python Path but version of pip is in python path + Scripts
So if you like to install module by pip configure your environment variable and make the right way of pip you like to use and install your module with pip
Tks

**Comment by ellensp** [comment]
you need to reactivate the virtual environment. ie do the following commands
source ~/.profile 
workon cv
cd Smart-Security-Camera
python main.py

**Comment by ayanasser** [comment]
Hi all ,

It's installed on python3 perfectly , 
but when i installed it on python2 it gave me this error 

`The directory '/home/biohelwan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: imutils in /usr/local/lib/python3.5/dist-packages (0.5.2)
`

**Comment by jrosebr1** [comment]
Delete your `.cache` directory first and then retry:

`$ rm -rf ~/.cache`

**Comment by Mathew3000** [comment]
Hey, my solution was to install imutils without sudo. I hope it helps someone.

**Comment by lamoboos223** [comment]
1. `sudo pip uninstall imutils`
2. `sudo pip install imutils`
3. `python3`
4. `import imutils`
5. if there is no error enter `exit()`

and congrats it works perfectly

**Comment by ajaytomgeorge** [comment]
most probably it is getting installed in global and not in local. Check if imutils is in this folder **C:\Program Files\Python37\Lib\site-packages**

copy paste imutils and imutils-0.5.2.dist-info folder in your local **C:\usersid\AppData\Roaming\Python\Python37\site-packages**

NB:AppData folder is hidden

or  `pip install --user  imutils`

**Comment by rvdrupal** [comment]
try this >> conda install -c conda-forge imutils

**Comment by amrfodd** [comment]
import pip  
pip.main(['install', 'imutils']) in Jypter Notebook

**Comment by TrabelsiRim** [comment]
Python 2.7

pip install imutils
or 
sudo pip install imutils (Raspberry)

Python 3

pip3 install imutils
or
sudo pip3 install imutils (Raspberry)

**Comment by SalmanCode** [comment]
> Hey guys I tried the uninstall method and re-installed from both within and outside the (cv) environment and still getting the "no module named imutils" error?
> Any suggestions. I've never had this problem previously.

Hello, did it finaly worked for you. I am having the same issue.
