### ISSUE TITLE
Missing method "corners_to_keypoints" in convenience.py

### ISSUE THREAD

**Issue by fabito** [jrosebr1/imutils#26]

**Comment by jrosebr1** [comment]
The `corners_to_keypoints` function has been moved to `imutils.feature.helpers`.

Please see:

https://github.com/jrosebr1/imutils/blob/master/imutils/feature/helpers.py

**Comment by fabito** [comment]
The gftt module still references conveience.py

**Comment by jrosebr1** [comment]
Ah, I see now. GFTT needs to be moved to the `feature` sub-module. I'll make sure this happens in the next release.

**Comment by jrosebr1** [comment]
Closed via `0.4.3`.
