### ISSUE TITLE
How to change Picamera parameters using the class pivideostream? 

### ISSUE THREAD

**Issue by BillieIsRunning** [jrosebr1/imutils#274]
Hello everyone,

I'm working on a python script which is used to capture videos at high framerates. Imutils and the picamera_fps_demo.py work well, but there is one issue. For my project, I have to adjust some of the camera parameters (ISO, shutter speed, ...). Can you tell me how to change these settings?

Thanks a lot for your help!

Regards!

**Comment by wernersbacher** [comment]
It should be possible via kargs:

```
vs = VideoStream(usePiCamera=True,
				 resolution=(400, 300),
				 iso=400,
				 framerate=20,
				 shutter_speed=int(1_000_000 * shutter_speed_seconds),
				 awb_mode='off',
				 exposure_mode='off')
```

**Comment by BillieIsRunning** [comment]
Thanks!
