### ISSUE TITLE
pip3 install issues

### ISSUE THREAD

**Issue by JAICHANGPARK** [jrosebr1/imutils#29]
hello 
I had some problem that installed library in python3.5 (windows)
I tried `pip3 install imutils`  & `pip install imutils`

but my error that show blow.
```
Could not find a version that satisfies the requirement imultis (from versions: )
No matching distribution found for imultis
```

**Comment by jrosebr1** [comment]
You must have had a typo in your command. Look at the output:

`Could not find a version that satisfies the requirement imultis`

Notice how `imultis` is incorrectly misspelled. It should read `imutils`.

The commands you've included in the report are correct, but they weren't the commands you typed into your terminal must have had the typo. Double-check your spelling of `imutils` and try again.

**Comment by JAICHANGPARK** [comment]
Thank you @jrosebr1 
I resolved this problem `pip3 install --upgrade imutils`

**Comment by shivanimutke** [comment]
pip3 install --upgrade imutils
               ^
SyntaxError: invalid syntax
