### ISSUE TITLE
imutils module not found

### ISSUE THREAD

**Issue by rkalghatgi** [jrosebr1/imutils#30]
Hi,

I'm using anaconda2 which is running Python 2.7.12. I did pip install imutils and it looks like it installed correctly, here is the result of pip show: 

Name: imutils
Version: 0.4.3
Summary: A series of convenience functions to make basic image processing functi
ons such as translation, rotation, resizing, skeletonization, displaying Matplot
lib images, sorting contours, detecting edges, and much more easier with OpenCV
and both Python 2.7 and Python 3.
Home-page: https://github.com/jrosebr1/imutils
Author: Adrian Rosebrock
Author-email: adrian@pyimagesearch.com
License: UNKNOWN
Location: c:\programdata\anaconda2\lib\site-packages
Requires:

However, in anaconda if I type "import imutils" it always says no module found. Should I be using a different version of imutils? I'm not sure how to resolve this issue. Any advice of help is much appreciated. Thanks!

**Comment by jrosebr1** [comment]
I'm not an anaconda user, so this is hard to diagnose. The version of imutils will not matter. Regardless, this is definitely an anaconda specific issue. I would try to figure out how anaconda installs packages, where they are installed to, and if they are using different virtual environments. Other than that, I'm not sure what else to suggest.

**Comment by rkalghatgi** [comment]
Thanks. I can't seem to get it to install. Since I have all of the python files, I'm going to have to just manually import the functions using several from "file path" import "your imutil_function" 

I hope this works. I'm trying to follow your pedestrian detection tutorial (http://www.pyimagesearch.com/2015/11/09/pedestrian-detection-opencv/) which is really awesome btw! Thanks!

**Comment by rafaellehmkuhl** [comment]
When you use pip install, it is probably installing on your non-anaconda Python environment. You need to point your to your Anaconda environment.
