### ISSUE TITLE
VideoStream.read() returns a none type object in ubuntu 16.04

### ISSUE THREAD

**Issue by prabushitha** [jrosebr1/imutils#31]
I used this code to check and it did print none in the console
```
from imutils.video import VideoStream
webcam = VideoStream(src=0).start()
while True:
    frame = webcam.read()
    print(frame)
```

**Comment by jrosebr1** [comment]
It sounds like your are unable to access the webcam on your system. It's 99% likely that your install of OpenCV wasn't compiled with video support. Re-install OpenCV and compile it with video support.

Alliteratively, the index of your `src` may be incorrect.

**Comment by prabushitha** [comment]
Yes @jrosebr1, I got this solved by compiling the opencv again. Previously I've installed opencv using apt-get.  I uninstalled the opencv and downloaed opencv from github repo and compiled it. Now it's working. If anyone having the same issue, follow this tutorial http://www.pyimagesearch.com/2015/07/20/install-opencv-3-0-and-python-3-4-on-ubuntu/ to install opencv.

**Comment by jrosebr1** [comment]
Nice job resolving the issue @prabushitha 😄
