### ISSUE TITLE
Package missing in Win-64 Anaconda

### ISSUE THREAD

**Issue by teknomo** [jrosebr1/imutils#36]
Cannot install imutils using anaconda in win-64 because package is missing (PackageNotFoundError)

![image](https://user-images.githubusercontent.com/9465043/30238469-e20b4ba0-957a-11e7-8746-e4e09b31d419.png)

**Comment by jrosebr1** [comment]
The `imutils` library is a [non-conda package](https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages) so you should use `pip`:

`pip install imutils`

And from there you can use `conda list` to verify that it has been installed.

**Comment by linksyncjameshwartlopez** [comment]
Im just wondering why im having issue installing imutils. It does not work for my case. Does anyone could give me a guidance. Thanks
![image](https://user-images.githubusercontent.com/17696792/34398022-faff6920-ebb5-11e7-91ec-86629111b74e.png)

**Comment by jrosebr1** [comment]
According to [this SO thread](https://stackoverflow.com/questions/46499808/pip-throws-typeerror-parse-got-an-unexpected-keyword-argument-transport-enco) you need to update `pip` in your conda environment.

**Comment by linksyncjameshwartlopez** [comment]
Thanks @jrosebr1

**Comment by PARULSHARM** [comment]
Just run 
`conda install pip`
It resolved the issue for me.

**Comment by maminizer** [comment]
try using" python -m pip install imutils" for python 3.x
