### ISSUE TITLE
setup imutils on Rasp Pi?

### ISSUE THREAD

**Issue by seacuello** [jrosebr1/imutils#37]
Hello is it possible to setup imutils on a Rasp Pi??

**Comment by jrosebr1** [comment]
Yes. First access the virtual environment you used to install OpenCV on your Raspberry Pi (assuming you used one of my tutorials: http://www.pyimagesearch.com/opencv-tutorials-resources-guides/):

`$ workon cv`

From there use `pip` to install `imutils`:

`$ pip install imutils`

**Comment by jrosebr1** [comment]
I'm going to go ahead and close this since I haven't heard back. Please refer to my install instructions in the previous comment.

**Comment by alaabadra** [comment]
hello Adrian  , is it possible to setup opencv3 on a Rasp Pi3 module b , in which i tried search in many websites but all it is failed (i can not install this opencv) , please i need her helping as soon as 
please .......
@jrosebr1

**Comment by jrosebr1** [comment]
Hey @alaabadra -- make sure you're taking a look at my website, PyImageSearch.com. I have many RPi install guides. This is the fastest one to get you up and running with OpenCV on the RPi:

https://www.pyimagesearch.com/2018/09/19/pip-install-opencv/
