### ISSUE TITLE
ImportError: No module named imutils

### ISSUE THREAD

**Issue by Loco123** [jrosebr1/imutils#39]
Hello,
I installed imutils in Ubuntu 16.04 using the next command:

sudo pip apt-get install imutils

I ran "pip list" and show me that imutils (0.4.3) is already installed, but when I tried to use it in a python script:

import imutils

show me the next error:

Traceback (most recent call last):
  File "/home/epic/Documentos/python test/OpenCV/curso/test2.py", line 3, in <module>
    import imutils
ImportError: No module named imutils

any idea what is wrong?

SALUDOS!!!!!!!!!!

**Comment by jrosebr1** [comment]
Hm, I think you have an issue with your command. This is *not* how you install a package with `pip`:

`$ sudo pip apt-get install imutils`

You should be doing:

`$ sudo pip install imutils`

To install globally on your system.

If you are using virtual environments, don't forget the `workon` command:

<pre>$ workon cv
$ pip install imutils</pre>

**Comment by Loco123** [comment]
My apologize my mistake when I open this "help request", thats right the command is:

sudo pip install imutils

I thougt that maybe the problem is that the installation was made under python 3.5 instead of python 2.7, any idea how to fix this problem, I ran again the installation command to see for more information and gave this:

The directory '/home/epic/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: imutils in /usr/local/lib/python3.5/dist-packages

after run with 

sudo -H pip install imutils

gave me the next message:

Requirement already satisfied: imutils in /usr/local/lib/python3.5/dist-packages

any idea how to fix it?

SALUDOS!!!!

**Comment by Loco123** [comment]
Ok I found the problem, after run:

sudo -H pip2.7 install imutils

All workied fine.

SALUDOS!!!!!

**Comment by jrosebr1** [comment]
Congrats on resolving the issue!

I'll go ahead and close this now.

**Comment by jrosebr1** [comment]
I'm not an Anaconda user myself but I think there may be some sort of Python/Pip discrepancy between your system version and your Python version. It looks like imutils is installed in Python 3.6. Perhaps trying launching Python 3.6 specific shell and trying the import:

```
$ python3
>>> import imutils
```

You should of course ensure that `python3` is indeed for your Python 3.6 Anaconda install.

**Comment by VibhaBelavadi** [comment]
I did try what you wrote, but I get the following error:

Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 21 2017, 18:29:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'imutils'

I suppose there might be a problem with the new anaconda version...don't know

Thanks!

**Comment by jrosebr1** [comment]
My only suggestion would be to ensure your `pip3` actual does indeed point to your Anaconda Python 3.6.2. You may have different Python 3.6 versions installed on your system. Sorry, I'm not sure.

**Comment by MRAwesome41297** [comment]
After installing imutils on windows by pip install imutils I got this error 

Traceback (most recent call last):
  File "C:\Users\OMKAR\Downloads\real-time-object-detection\real_time_object_detection.py", line 5, in <module>
    from imutils.video import VideoStream
ImportError: No module named imutils.video


what should i do????

**Comment by jrosebr1** [comment]
It sounds like `imutils` has not been properly installed on your system. Double-check that you have properly installed it into your Anaconda environment and not your system Python.

**Comment by nanowinner** [comment]
> My only suggestion would be to ensure your `pip3` actual does indeed point to your Anaconda Python 3.6.2. You may have different Python 3.6 versions installed on your system. Sorry, I'm not sure.

This did it for me. I used the instructions found for **activating** my virtual environment here: 
https://packaging.python.org/guides/installing-using-pip-and-virtualenv/#activating-a-virtualenv

One activated my console now printed: 
**(venv)** (base) C:\Users\<user>\PycharmProjects\keras-multi-label>

Since the console was pointing to (venv) I could then install imutils and it was then made available to the project. 

Thanks!

**Comment by tejasri19** [comment]
pip install imutils
This worked fine with me in conda environment.

**Comment by iampujan** [comment]
try using this command.
I faced the same situation and this worked.
`pip install –upgrade imutils (pip3 if `python3)`

**Comment by ibrahimqazi** [comment]
> Hello,
> 
> I'm instaling mutils using: sudo H pip3 install mutils
> and the version of pip3 and python are 10.0.1 and 3.6 respectively
> 
> It gets successfully installed but when I try to import it, it shows "No module named 'mutils'".
> 
> Also when I try to install it again it says:
> Requirement already satisfied: mutils in /anaconda3/lib/python3.6/site-packages (1.0.5)
> 
> Please help me out. Thanks!!

I think you should check your spelling its

>  imutils

 not 

> mutils

**Comment by PUPAN789ER** [comment]
> Hm, I think you have an issue with your command. This is _not_ how you install a package with `pip`:
> 
> `$ sudo pip apt-get install imutils`
> 
> You should be doing:
> 
> `$ sudo pip install imutils`
> 
> To install globally on your system.
> 
> If you are using virtual environments, don't forget the `workon` command:
> 
> $ workon your_env_name
> $ pip install imutils

Good job!

**Comment by mughuara** [comment]
Hello. I have the same problem. I a virtual env, so, this is the way I installed imutils:

workon cv
sudo -H pip3.7 install --upgrade imutils

it says that it has been successfully installed. but when I do:

pip3.7 list

imutils doens't appears on the packages list.


Can someone help me? None of the above answers had been useful yet. :(

**Comment by jrosebr1** [comment]
I would _strongly_ recommend that you learn how to use Python virtual environments. You are installing imutils _incorrectly_. To install it inside a virtualenv you would:

```
$ workon your_env_name (or however you access your virtualenv)
$ pip install imutils
```

DO NOT use sudo or any other pip commands with specific versions as those will install imutils _outisde_ the virtualenv.

Again, do not blindly copy and paste commands -- that's a recipe for failure. Learn how the commands work and what they are doing. Spend 10 minutes educating yourself, it will save you hours of frustration.

**Comment by mughuara** [comment]
Thank you very much! I'm sorry for the mistake, I'm new at this whole thing so it's too much information to take in a short time. 

Now it works fine 💃

**Comment by panimalariit** [comment]
after runing the  command "sudo -H pip2.7 install imutils"
i got the below error
sudo: pip: command not found
how to solve this  problem

**Comment by Omkar-Darekar** [comment]
you can do ------------->>>>
sudo apt install pip
sudo apt install pip3



*Omkar Ashok Darekar*+91 968 915 4008
LinkedIn <http://www.linkedin.com/in/omkar-darekar>  Twitter
<https://twitter.com/OmkarDarekar_>  Instagram
<https://www.instagram.com/mr_awes0me__/>  Facebook
<https://www.facebook.com/omkar.darekar.96>

**Comment by amrfodd** [comment]
import pip  
pip.main(['install', 'imutils'])  
Try This in Jupyter Notebook

**Comment by neha210** [comment]
please can anyone help me out with what command could be helpful to install imutils in jupytor notebook

**Comment by iampujan** [comment]
> please can anyone help me out with what command could be helpful to install imutils in jupytor notebook

!pip install <package>

**Comment by bishab** [comment]
> import pip
> pip.main(['install', 'imutils'])
> Try This in Jupyter Notebook

This helped me. Thanks!

**Comment by vc-orange** [comment]
> import pip pip.main(['install', 'imutils']) Try This in Jupyter Notebook

thank you, it works
