### ISSUE TITLE
imutils import error in pythin 3.6

### ISSUE THREAD

**Issue by 10dodoAI** [jrosebr1/imutils#40]
I have installed imutils using `pip3 install imutils` with python 3 version as 3.6.3 .But when I try to imprt it it gives me ImportError for imutils, althought the requirement is already satisifed in  /usr/lib/python3.6/site-packages.

**Comment by 10dodoAI** [comment]
Issue resolved by self compiling the setup.py  with cmd arg as 'install'.So, closing the issue.

**Comment by jrosebr1** [comment]
Nice, congrats on resolving the issue!

My guess here is that you have two Python 3 versions installed (likely Python 3.5 and 3.6). The `pip3` command likely references Python 3.5. There is probably a `pip36` command on your system that points to Python 3.6. That might be worth investigating in the future if you need to install other packages.

**Comment by 10dodoAI** [comment]
I investigated for this but  I have just two versions of python 3.6.3 and python 2.7.12.
Also after pip3 install ,i  got the module in site packages of python3.6 but  python 3.6 couldn't import it.Also the conda method of installation failed.
 So, downloading from here and then `python3 setup.py install `  worked only.
