### ISSUE TITLE
PiVideoStream.read() gives me worked on image????

### ISSUE THREAD

**Issue by mckeevio** [jrosebr1/imutils#51]
Firstly I have a local copy of your pivideostream.py which I have amended to do 640x480
it is attached

Then I have a program which is looking at the frames 
They are coming  into a cam variable via vs.read()
It highlights any blue areas and the final image is stored in disp variable

The problem is that sometimes I am getting what I put out as disp back from vs.read()
You can see double green outlines sometimes in the program. Very Weird...
Have you seen this behaviour before?

You should be able to replicate if you run the attached code with my copy of pivideostream in the same directory and put something
 blue under the camera

[help.zip](https://github.com/jrosebr1/imutils/files/1767296/help.zip)

**Comment by jrosebr1** [comment]
That is strange, but I'm not sure what would be causing that issue and I have not seen that particular issue before. Could you try a different Raspberry Pi camera module just to see if it's a hardware issue? That would at least determine if it's hardware vs. software.

**Comment by mckeevio** [comment]
I found a solution where I had to  use dist=cam.copy instead of dist=cam
Just assigning only links me to the same memory as the camera output

I think I was querying before a frame was ready

The cam.copy makes me lose about 5 frames per second which takes me down to
~7fps
Any ideas for a quicker implementation?

**Comment by jrosebr1** [comment]
Awesome, congrats on resolving the bug 😄 

As far the FPS, have you tried installing an optimized version of OpenCV for the Pi:

https://www.pyimagesearch.com/2017/10/09/optimizing-opencv-on-the-raspberry-pi/

That should help speed things along.

**Comment by jrosebr1** [comment]
Since the original issue was solved I am going to close this issue.
