### ISSUE TITLE
Weird "flickering" when using VideoStream.read

### ISSUE THREAD

**Issue by xoxota99** [jrosebr1/imutils#54]
I'm seeing some strange flickering (like dropping every second frame or something) when processing frames obtained through VideoStream.read() through cv2.dilate and cv2.absdiff.

Example of Working, "pure OpenCV" code: https://gist.github.com/xoxota99/dd5a3c412a7505faa7d2179e8417b517

Equivalent code, using VideoStream, causing flickering.
https://gist.github.com/xoxota99/46019b359a15e180b18db3e6f4502b57

I notice that the framerate is (obviously) much higher using VideoStream, but is there a way to avoid the dropped frames?

**Comment by xoxota99** [comment]
Passing the VideoStream.read() return value directly to imshow does NOT display the flickering. IT only happens if you process the frame.

**Comment by xoxota99** [comment]
Looks like VideoStream.read() will periodically (regularly?) return the same frame twice in a row. When calling absdiff, it'll return an empty array. I can get around the flickering by calling numpy.any() on the resulting array, and skipping imshow if it returns false.

**Comment by jrosebr1** [comment]
> Looks like VideoStream.read() will periodically (regularly?) return the same frame twice in a row. 

This is a feature, not a bug. The `VideoStream` object will return whatever the _current_ `frame` is from the queue, but not necessarily the next _brand new_ frame.

Our goal is to achieve as high frame throughout as possible; however, for incredibly simplistic frame processing pipelines as yours, the loop actually completes before a brand new frame is even available on the camera. The vast majority of frame processing pipelines are not as fast as yours. I hope that helps clear up the issue.

**Comment by xoxota99** [comment]
Yep! Closing...
