### ISSUE TITLE
"resolution" and "framerate" parameters are ignored by VideoStream when using webcam source

### ISSUE THREAD

**Issue by xoxota99** [jrosebr1/imutils#55]
According to https://github.com/jrosebr1/imutils/blob/master/imutils/video/videostream.py , the constructor arguments for resolution and fps are only used if the PI Camera is the source for the the videostream. Is this intentional?

**Comment by jrosebr1** [comment]
Yes. If you are using a `cv2.VideoCapture` then any properties would be need to be set via the `.set` method of the object.

**Comment by jrosebr1** [comment]
I'll add that a better implementation of `VideoStream` would accept a pre-initialized `PiVideoStream` and `cv2.VideoCapture` object. This would allow the user to add any customizations to the object that they see fit and then pass it into `VideoStream` to make it threaded.

However, this class _must_ be kept backwards compatible as many other implementations rely on it, as do all (current) articles on the PyImageSearch blog.

Another option would be to have a `stream` parameter to the constructor which is a pre-instantiated `PiVideoStream` or `WebcamVideoStream`.

Checking the type of the `src` object would fix it, but the `VideoStream` class in particular would need an overhaul.

**Comment by xoxota99** [comment]
Feature request, then? Or "Won't Fix"?

**Comment by jrosebr1** [comment]
It's a feature request but it needs to be carefully done to ensure backwards compatibility.

**Comment by Momilijaz96** [comment]
So in conclusion how can we achieve a faster frame rate with videostream?

**Comment by jrosebr1** [comment]
@Momilijaz96 [This PR](https://github.com/jrosebr1/imutils/pull/149), which I'll merge in next week, will allow for arbitrary `cv2.VideoCapture` parameters to be set within `VideoStream`.
