### ISSUE TITLE
How to rotate the output frame？

### ISSUE THREAD

**Issue by datamonday** [jrosebr1/imutils#56]
My picamera output is inverted, how should I modify the program? thank you very much!

**Comment by jrosebr1** [comment]
I would first check the `picamera` usage:

https://www.raspberrypi.org/documentation/usage/camera/python/README.md

You can set either `.hflip` or `.vflip`.

If you want to perform the flip using OpenCV, use the `cv2.flip` function.

**Comment by datamonday** [comment]
Thank you! You are so good !
