### ISSUE TITLE
pip install imutils is not installing in python 2.7

### ISSUE THREAD

**Issue by Mohammad-Khalid23** [jrosebr1/imutils#58]
C:\Python27\Scripts>pip install imutils
Collecting imutils
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec
tion broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x000000000391C518>, 'Connection to 10.1
.0.11 timed out. (connect timeout=15)')': /simple/imutils/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connec
tion broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x000000000391C1D0>, 'Connection to 10.1
.0.11 timed out. (connect timeout=15)')': /simple/imutils/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connec
tion broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x000000000391C0F0>, 'Connection to 10.1
.0.11 timed out. (connect timeout=15)')': /simple/imutils/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connec
tion broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x000000000391CDA0>, 'Connection to 10.1
.0.11 timed out. (connect timeout=15)')': /simple/imutils/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connec
tion broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.conne
ction.VerifiedHTTPSConnection object at 0x0000000003912EB8>, 'Connection to 10.1
.0.11 timed out. (connect timeout=15)')': /simple/imutils/
  Could not find a version that satisfies the requirement imutils (from versions
: )
No matching distribution found for imutils

**Comment by jrosebr1** [comment]
According to your error it looks like your internet connection is dropping out or is not stable for whatever reason. Double-check your internet connection and try to install again.

**Comment by Mohammad-Khalid23** [comment]
@jrosebr1  internet connection is okay , its still giving error

**Comment by jrosebr1** [comment]
For whatever reason it looks like `pip` is trying to connect to `10.1.0.11` which seems like an internal IP address. It sounds like something may be wrong with your DNS or you are behind some sort of firewall. I'm honestly not sure what may be causing that as it's likely a system setting.

**Comment by jrosebr1** [comment]
I am closing this out now as it's not related to the `imutils` library.
