### ISSUE TITLE
vs.read() stuck when I rerun the script again

### ISSUE THREAD

**Issue by ahangchen** [jrosebr1/imutils#59]
I use this code to read the image from Logitech C720 and save them to disk in Raspberry 3B+ Raspbian stretch.

Everything goes well when I run the script for the first time, but when I rerun the script again. It was stuck as vs.read(), and I have to cancel it by CTRL+C.

Is there anything wrong with my code?

```python
from imutils.video import VideoStream
from imutils.video import FPS
import datetime
import imutils
import time
import cv2
import os 

os.system("mkdir record")
print("[INFO] starting video stream...")
vs = VideoStream(src=0).start()
fps = FPS().start()


i = 0
while i < 2000:
    frame = vs.read()
    if frame is None:
        continue
    timestamp = datetime.datetime.now()
    cv2.imwrite("record/%d.jpg" % i, frame)
    print i
    fps.update()
    i += 1

fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))
vs.stop()
```

**Comment by jrosebr1** [comment]
You say "stuck" at `vs.read()` -- are you sure it's "stuck"? Have you inserted `print` statements to debug this? What specifically have you done to try to debug the script?

**Comment by ahangchen** [comment]
I follow your suggestion and add print in the if statement:

```python
from imutils.video import VideoStream
from imutils.video import FPS
import datetime
import imutils
import time
import cv2
import os 

os.system("mkdir record")
print("[INFO] starting video stream...")
vs = VideoStream(src=0).start()
fps = FPS().start()


i = 0
while i < 2000:
    frame = vs.read()
    if frame is None:
        print 'read none'
        continue
    timestamp = datetime.datetime.now()
    cv2.imwrite("record/%d.jpg" % i, frame)
    print i
    fps.update()
    i += 1

fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))
vs.stop()
```

And find that in the second time I run the script, only 'read none' output, that means vs.read() return None in the second execution.

**Comment by ahangchen** [comment]
I find the cause... 
VideoStream.stop() in webcamstream doesn't release the camera!
And I find someone has made a fix for this in #47 .
I think it's necessary to merge this fix and update pip source as soon as possible.

**Comment by jrosebr1** [comment]
Congrats on resolving the issue. I'll look into this further and try to replicate.

**Comment by ahangchen** [comment]
emmmm, after more test, I find it doesn't work necessarily, even if I use raw OpenCV code to handle the WebCamera. It still failed.

```python
import datetime
import imutils
import time
import cv2
import os 

os.system("mkdir record")
print("[INFO] starting video stream...")
stream = cv2.VideoCapture(0)

i = 0
while i < 100:
    _, frame = stream.read()
    if frame is None:
        print'read none'
        continue
    cv2.imwrite("record/%d.jpg" % i, frame)
    print i
    i += 1
stream.release()
```

So I think it's something to do with C720 or OpenCV itself.
