### ISSUE TITLE
paths.py - replacing space with slash+space

### ISSUE THREAD

**Issue by m3rik** [jrosebr1/imutils#61]
Hi!

First of all, thanks for the library. Very useful!
Second, I wanted to ask you why do you replace space with slash+space in paths.py? Is this a bug or something you've done on purpose?

`imagePath = os.path.join(rootDir, filename).replace(" ", "\\ ")`

PS: I'm using Windows and Python3.

**Comment by jrosebr1** [comment]
It's not a bug. It's to escape file paths that have spaces in them. If you're on a Unix machine try to auto-tab complete a file path that has spaces in them.

It will change:

`$ cd Foo Bar`

To:

`$ cd Foo\ Bar`

**Comment by m3rik** [comment]
Yes. You are write on Unix System. Try reading an image with the path escaped on Windows. It will return None because "C:\\ugly path\\image.jpg" is transformed into "C:\\ugly\\ path\\image.jpg" and that path does not exists.
Please, don't get me wrong, I hate spaces in paths!

Cheers.

**Comment by jrosebr1** [comment]
Got it, I see the issue. I'll re-open this in case any user wants to take a crack at it. Spaces in file paths are a pain. I try to avoid them whenever possible and they really shouldn't be used. 

I'm tempted to say "it's a feature not a bug" to make people stop using spaces in file paths; however, that's not entirely fair ;-)

**Comment by skypanther** [comment]
There's no reason to manually add the slash in there with that `replace` operation. os.path handles that for you automatically. For example, this works fine (assuming the directory and file exist):

```
import os

file_path = os.path.join('.', 'folder name with spaces', 'somefile.txt')

if not os.path.isfile(file_path):
    raise ValueError(f'Cannot read file at {file_path}')
with open(file_path) as f:
    print(f.read())
```

results in 

```
≫ python file_test.py
this is some file
```

I don't have a Windows computer to test that on, but according to the docs it should be fine. If you were targeting only python 3.4+ you could use the pathlib module instead.

**Comment by jrosebr1** [comment]
The `imutils` library is meant to be compatible with both Python 2.7 and Python 3 otherwise, I agree, `pathlib` would be ideal here. I don't have a Windows system either so I'm going to keep the issue open until we test on Windows.

**Comment by andreasgou** [comment]
Hi Adrian, note that b.slash + space doesn't work in OSX either, running python3 in Sierra 10.12.6.
I'm talking about the file names, so I had to remove the backslash with another replace.
About the spaces that shouldn't exist, well, this is a limitation we programmers learned to live with but time goes on and issues like that are supposed to be eliminated, don't they?

**Comment by wlinna** [comment]
It doesn't work on Kubuntu 18.04 either. At least `cv2.imread` doesn't understand paths that are escaped this way (`cv2.imread` just returns `None`). After commenting out the escaping part, `cv2.imread` can read the image just fine.

I have OpenCV 3.4.1 and Python 3.6.5.

**Comment by salvatore373** [comment]
Maybe my simple solution can be useful to you too. I made an inverse replacing. It converts to the original version the paths edited by `paths.py` adding a slash before the spaces:

`working_path = slash_space_path.replace("\\ ", " ")`

where `slash_space_path` is a path edited in `paths.py`, where spaces have been replaced by `\ `
