### ISSUE TITLE
In every project that I'm using this I get 'ZeroDivisionError: float division by zero'

### ISSUE THREAD

**Issue by zubairahmed-ai** [jrosebr1/imutils#65]
I have upgraded `imutils` using `pip install -upgrade imutils` but in every project I get the following error

`File "D:\ProgramData\Anaconda3\envs\facialrec\lib\site-packages\imutils\video\fps.py", line 33, in fps
    return self._numFrames / self.elapsed()
ZeroDivisionError: float division by zero`

**Comment by jrosebr1** [comment]
I think you may be forgetting to call `.start()` when starting the video stream _or_ in `FPS`. The other possibility is that you are trying to compute the FPS when no actual frames have been read by your camera sensor. Double-check OpenCV can access your camera.

**Comment by zubairahmed-ai** [comment]
`.start()` was definitely called but it could be that OpenCV didnt get access to camera or video frames, in my  current case it's just a library downloaded from GitHub that I'm trying
I'll double-check
