### ISSUE TITLE
Package importation error on perspective module

### ISSUE THREAD

**Issue by eronlloyd** [jrosebr1/imutils#70]
I'm experiencing trouble accessing the modules in the `imutils` package, running in an Anaconda virtual environment. As you'll see in the console output below, I'm in the env and the package itself imports, but none of the modules are accessible. The package was successfully installed using pip in the env, which I also include in the output.

```
(datasci) saturn:cvtraining eronlloyd$ pip install imutils
Collecting imutils
  Downloading https://files.pythonhosted.org/packages/15/ba/24272ac57159cf255959f9298b8e42f00528be90ce4ccd274b604ae5e32d/imutils-0.4.6.tar.gz
Building wheels for collected packages: imutils
  Running setup.py bdist_wheel for imutils ... done
  Stored in directory: /Users/eronlloyd/Library/Caches/pip/wheels/cb/58/9b/7debccbc53159611f67cc7e2e3ed37b217e56e9b40e7ba80c3
Successfully built imutils
Installing collected packages: imutils
Successfully installed imutils-0.4.6
(datasci) saturn:cvtraining eronlloyd$ ls /Users/eronlloyd/anaconda/envs/datasci/lib/python3.6/site-packages/imutils
__init__.py		face_utils		paths.py
__pycache__		feature			perspective.py
contours.py		io			video
convenience.py		meta.py
encodings.py		object_detection.py
(datasci) saturn:cvtraining eronlloyd$ ipython
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import imutils

In [2]: dir(imutils)
Out[2]: 
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'cv2',
 'np',
 'resize',
 'rotate',
 'translate']

In [3]: from imutils import perspective
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-1c2f33893220> in <module>()
----> 1 from imutils import perspective

ImportError: cannot import name 'perspective'
```
I've seen others have basic installation issues with pip or their virtualenv, but I believe this more directly related to the package itself. Can anyone confirm successful installation in a conda env?

**Comment by jrosebr1** [comment]
I'm not an Anaconda user myself so I cannot replicate this specific error. When you launch `ipython` can you confirm that the `site-packages` directory being used is `/Users/eronlloyd/anaconda/envs/datasci/lib/python3.6/site-packages/imutils`?

I would assume it is, but it's worth double-checking.

This is the part that really confuses me:

> In [1]: import imutils
> ...
> In [3]: from imutils import perspective

You can import the `imutils` library itself but not any of the submodules. It appears that all of the submodules are missing.

I'm validated using v0.4.6 and it does indeed have all modules:

```
$ pip freeze | grep 'imutils'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
imutils==0.4.6
(dl4cv)malcolm:~ adrianrosebrock$ python
Python 3.5.0 (default, Sep 23 2015, 04:42:00) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from imutils import perspective
>>> import imutils
>>> dir(imutils)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'auto_canny', 'build_montages', 'check_opencv_version', 'convenience', 'find_function', 'is_cv2', 'is_cv3', 'meta', 'opencv2matplotlib', 'perspective', 'resize', 'rotate', 'rotate_bound', 'skeletonize', 'translate', 'url_to_image']
```

**Comment by jrosebr1** [comment]
Actually, can you `ls` the contents of your current directory? Did you download source code from the PyImageSearch blog that contained the `imutils` package? You may have a Python module named `imutils` in your current working directory and that is the one being imported rather than the one you pip installed.

**Comment by eronlloyd** [comment]
That was it... I'm using the project folder I worked through the book with, and obviously that same named module exists there. Thanks, Adrian!

**Comment by jrosebr1** [comment]
Awesome, I'm glad that was it :-)
