### ISSUE TITLE
problem with filename with spaces

### ISSUE THREAD

**Issue by chuyee** [jrosebr1/imutils#75]
Hi Adrian,

It seems like cv2.imread() doesn't like the backslash prefix for space in a file name. It turns None in this case. I understand there must be other cases the backslash is required. However should we have a better way to handle this?

My cv2 is 3.2.0, python is 3.6.5 on Ubuntu 18.04. If the filename contains a space, cv2.imread(imutile.paths.list_images(filename_with_space)) returns None. It can be fixed if I modify https://github.com/jrosebr1/imutils/blob/master/imutils/paths.py line 24 as below (remove the .replace(" ", "\\ ") part).

imagePath = os.path.join(rootDir, filename)

Thanks,
-yi

**Comment by jrosebr1** [comment]
Hey @chuyee, you'll want to see #61 where we are handling the issue there. I'm going to close this ticket so discussion can continue in #61.
