### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by qlerebours** [jrosebr1/imutils#76]
Hello,

I have a python3 script on my computer that I can run with `python3 motion_detection.py` and that works, I tried to use it on my Raspberry and something fails with message `Illegal instruction`. The line that throws this error is: `frame = imutils.resize(frame, width=500)`

Here is the minimalist sample of code:

    import imutils
    import cv2
    frame = cv2.imread('test.jpg')
    frame = imutils.resize(frame, width=500)

I'm sure that frame is not None because I tried to save it and it worked.
I'm a bit confused because there is no more explaination that `Illegal instruction`
I checked the version of imutils that is the same on my computer that on the Raspberry (0.4.6)

Can someone help me please ?

**Comment by pageauc** [comment]
I have tried this on a several of my raspberry pi 3 computers 
1 running Jessie and Stretch   
2  using opencv 3.4.2
3 using python2 and python3 per code below (just added imwrite to see that image was OK.     
4 using latest imutils    

No errors were reported and no illegal instructions reported.   You might try running dos2unix on the script file to make sure it is in unix format since there may be hidden character causing problem.   Just a thought.

    import imutils
    import cv2
    frame = cv2.imread('test.jpg')
    frame = imutils.resize(frame, width=500)
    cv2.imwrite('test500.jpg', frame)

**Comment by jrosebr1** [comment]
I don't think this is an `imutils` problem, it sounds like an OpenCV problem. If you want to confirm imutils vs. OpenCV, swap out the `imutils.resize` call with a `cv2.resize` call and that will tell you. But again, I'm 99% sure there is a problem with your OpenCV install so you may want to compile and re-install OpenCV.

**Comment by pageauc** [comment]
If you are interested, I have a menu driven opencv 3.4.2  installation that automates most of the install process.  Allows customization of cv version and temporary file location.  Just added an Auto unprompted install menu pick.  See GitHub project here https://github.com/pageauc/opencv3-setup
Regards

**Comment by qlerebours** [comment]
Thanks for your replies
I tried to make a complete reinstallation of python3, pip3, opencv and imutils (but not the reinstallation of the Raspberry OS) and I still have the same problem.
I also tried:
`$ python3`

```
import imutils
import cv2
frame = cv2.imread('test.jpg')
frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
cv2.imwrite('testresize.jpg', frame)
``` 
and it worked, when replacing `frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)` by `frame = imutils.resize(frame, width=500)` still throw a `Illegal instruction`

Thanks @pageauc for your install tool, i'll have a try.
I think that the next step for me is to completely reinstall my Raspberry

**Comment by pageauc** [comment]
The only time I have seen illegal instruction is once when testing my menu driven opencv install.  I inadvertently added NEON directive on a RPI2.  NEON directive can only be used on RPI3's.  NEON is an ARM optimization for better video and media performance.

My menu driven install accommodates for this and detects if the RPI is a 2 or 3 and sets directory off if it is RPI2.  I updated the https://github.com/pageauc/opencv3-setup project to ver 3.1.  Now tells you what current opencv version you are running and warns you if you are trying to install the same version.

I would appreciate feedback on your experience with my menu driven opencv install from source project.

Regards 
Claude ...

**Comment by qlerebours** [comment]
I'm currently trying to reinstall with your tool @pageauc 
CMake is soooo long... Maybe I will completely reinstall the Raspberry

**Comment by qlerebours** [comment]
Do you know how I could get a stacktrace for this error ? I'm not expert in python, I tried with: 
```
try:
    imutils.resize......
except:
    print("An error occured ...")
    traceback.print_exc()
```

But i can't get a stacktrace

**Comment by qlerebours** [comment]
Hello @jrosebr1 @pageauc 
I have some news about this issue:
I completely reinstalled my Raspberry Pi Zero, reinstalled cv2 and imutils and I still have the error. Here are the steps I followed: 
 - formatted the SD card in ext4
 - enabled ssh to connect from my computer
 - `sudo pip3 install opencv-python imutils numpy scipy`
 - `sudo apt-get install libatlas-base-dev libjasper-dev libqtgui4 python3-pyqt5 libqt4-test`
 - `wget http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg`
 - `mv profile_user.jpg test.jpg`
 - `python3`
 - `>>> import cv2`
 - `>>> import imutils`
 - `>>> frame = cv2.imread('test.jpg')`
 - `>>> type(frame)`   ==> `<class 'numpy.ndarray'>`
 - `>>> frame = imutils.resize(frame, width=500)` ==> `Illegal instruction`

**Comment by qlerebours** [comment]
As I called `imutils.resize(frame, width=500)` I tried to execute the same code as the resize method:
```
>>> import cv2
>>> import imutils
>>> frame = cv2.imread('bla.jpg')
>>> (h, w) = frame.shape[:2]
>>> h
750
>>> w
750
>>> r = 500 / float(w)
>>> r
0.6666666666666666
>>> dim = (500, int(h * r))
>>> dim
(500, 500)
>>> resized = cv2.resize(frame, dim, cv2.INTER_AREA)
>>> cv2.imwrite('blabla.jpg', resized)
True
```

And everything was ok... 
I will use this in my code (not the imutils method) and I will close the issue, feel free to repopen if someone has the same problem but for the moment, it seems that I'm the only one to have this issue

Thanks for your help ! :)

**Comment by jrosebr1** [comment]
Oh man, I wish I knew you were using a Pi Zero, @qlerebours. The Pi Zero can be a real pain to use OpenCV on as its a slightly different architecture which ends up causing massive issues. If at all possible you should try to use a Pi 3. I understand that in some situations you need the Zero, but the Pi 3 is my general recommendation.

If the `interpolation` is breaking the function call you may want to try a different interpolation. The value `cv2.INTER_AREA` is used by default. Do you still get an illegal instruction for `cv2.INTER_CUBIC` and the other interpolation methods?

**Comment by Garrus007** [comment]
I've got same error using Raspberry Pi model B and Debian Stretch. I compiled OpenCV 3.4.3. When I started OpenCV I get error `Failed to load module "canberra-gtk-module"`, but OpenCV still works. But If I resize `imshow` window I'll get `Illegal instruction` error. Then I installed `libcanberra-gtk-module` and there were no errors anymore. Maybe this has some relation to your errors.

**Comment by flying4fun** [comment]
@jrosebr1 I can confirm that changing the `interpolation` from `cv2.INTER_AREA` to `cv2.INTER_CUBIC` on the Pi Zero appears to work.
