### ISSUE TITLE
Release a c++ implementation?

### ISSUE THREAD

**Issue by sazr** [jrosebr1/imutils#77]
Hello, this is a great library. Do you have plans to release a c++ opencv implementation?

**Comment by minooei** [comment]
Actually one day I started to rewrite this repository in c++ but didn't get it done yet 
here is the repo
[https://github.com/BeaverMoon/imutils](url)
thanks goes to Adrian for this great library :)

**Comment by jrosebr1** [comment]
Hey @sazr, I don't have any plans to create a C++ version of this library. I simply don't have enough time.

**Comment by thedevmanek** [comment]
I do not know if anyone is still interested but I have created both static and dynamic c++ libraries for imutils it can be found here https://github.com/thedevmanek/imutils-cpp
