### ISSUE TITLE
AttributeError: module 'imutils.face_utils' has no attribute 'FACIAL_LANDMARKS_IDXS'

### ISSUE THREAD

**Issue by gangubai** [jrosebr1/imutils#84]
imutils module is installed in my pc but still i am getting this error.I have python 3.6.4 version.
Please if anyone find the solution for this ,please let me know.
Thanks in advance!!

python3 detect_blinks.py --shape-predictor shape_predictor_68_face_landmarks.dat
[INFO] loading facial landmark predictor...
Traceback (most recent call last):
  File "detect_blinks.py", line 59, in <module>
    (lStart, lEnd) = face_utils.FACIAL_LANDMARKS_IDXS["left_eye"]
AttributeError: module 'imutils.face_utils' has no attribute 'FACIAL_LANDMARKS_IDXS'

**Comment by jrosebr1** [comment]
Change `FACIAL_LANDMARKS_IDXS` to `FACIAL_LANDMARKS_68_IDXS` and it will work.

**Comment by kshivam99** [comment]
It still doesnt work.
module 'imutils.face_utils' has no attribute 'FACIAL_LANDMARKS_68_IDXS'

**Comment by jrosebr1** [comment]
You need to update your `imutils` install to the latest version:

```
$ pip install --upgrade imutils
```

**Comment by marcelogere** [comment]
Hello everyone, in my case I get an error with "face_utils.FACIAL_LANDMARKS_68_IDXS", I just removed the "68" and then it worked

**Comment by jrosebr1** [comment]
It sounds like you're using an old version of imutils, @marcelogere. See my reply to @kshivam99 -- you need to upgrade your imutils version.
