### ISSUE TITLE
ImportError: No module named imutils

### ISSUE THREAD

**Issue by jasch-shah** [jrosebr1/imutils#87]
User-MacBook-Pro:~ user$ sudo pip install imutils

Collecting imutils
Installing collected packages: imutils
Successfully installed imutils-0.5.1
User-MacBook-Pro:~ user$ -H
-bash: -H: command not found
User-MacBook-Pro:~ user$ sudo -H pip install imutils
Requirement already satisfied: imutils in /usr/local/lib/python2.7/site-packages (0.5.1)

Installed imutils for Python2.7
and when I checked whether it is importing imutils library successfully or not then it displayed the following error message:

User-MacBook-Pro:~ user$ python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import imutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named imutils

What is the problem here and how to fix it??

**Comment by jrosebr1** [comment]
It's a Python path issue of some sort. Make sure that your `python` command is launching the Python shell for `/usr/local/bin/python2.7`. My guess is that you have multiple Python installs and your `pip` install points to a different version of Python.

**Comment by jasch-shah** [comment]
@jrosebr1  How should I fix this such that the python version which contain all my opencv and other modules installation remains unaffected and the redundant one get removed without affecting my existing setup.

**Comment by jrosebr1** [comment]
It sounds like you need Python virtual environments. Have followed one of my guides to install OpenCV?

https://www.pyimagesearch.com/opencv-tutorials-resources-guides/

If so, you will have Python virtual environments installed, ensuring your existing setup is not changed.

Additionally, you should read the following guide if you are new to Python virtual environments:

https://realpython.com/python-virtual-environments-a-primer/

**Comment by jasch-shah** [comment]
Thank You @jrosebr1

**Comment by tejasri19** [comment]
pip install imutils 
This worked fine with me in conda environment.
