### ISSUE TITLE
Why not use IOU in non_max_suppression?

### ISSUE THREAD

**Issue by GongweiChen** [jrosebr1/imutils#88]
Hi, to my knowledge, IOU (interaction over union) is the common metric to decide whether to reject the bounding box in Object Detection. But in following script, 
https://github.com/jrosebr1/imutils/blob/d277bb7118f265d4ef7877817c9a1824e423dc13/imutils/object_detection.py#L57

the `overlap` is not IOU score. So I am wonder why you not use IOU?

In addition, when using your code (no IOU), the number of bboxes after NMS is not  proportional to `overlapThresh`. But it comes true, when using IOU.

**Comment by jrosebr1** [comment]
Hey @GongweiChen -- I think you may have a bit of confusion regarding IoU. The following tutorial and comment should help clarify it for you:

- https://www.pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/
- https://www.pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/#comment-410517

**Comment by GongweiChen** [comment]
You can see in following code, 

https://github.com/rbgirshick/rcnn/blob/43b0334e96e9e910bc45c94902a093b5a6f35d0a/nms/nms.m#L36-L54

IOU score is used for rejecting the bboxes. And the same is in `fast-rcnn` and `py-faster-rcnn`.
It seems like Ross Girshick changed the implementation of NMS in `rcnn` repository.
I am wonder why has this change? Thanks!

**Comment by jrosebr1** [comment]
I'm not sure why Girshick et al. may have made those changes. It could be specific to the dataset they are working with. Keep in mind that NMS, IoU, and most importantly, mAP definitions can vary depending on what benchmark dataset you are using. My guess is that it may be specific to a dataset Girshick et al. was working with for their publication. You may want to reach out to them.

**Comment by GongweiChen** [comment]
Thanks for your reply and suggestions!
